### ISSUE TITLE
The building drones of both players try to complete the same action at a time.

### ISSUE THREAD

**Issue by TahoeBennie** [hubastard/nebula#147]
Not sure if its a bug or not, but whenever one player tries to build, all of the other players' construction drones also try to build the same thing even if its further away than who originally placed the building. Additional bug: players cannot see each other's building drones, just their own. No screenshots are available as I am reporting this bug after my friend was no longer online.

**Comment by Baldie-dev** [comment]
Everything is fixed here in PR: https://github.com/hubastard/nebula/pull/145

**Comment by SuperHydroman** [comment]
As of version 0.9 me and a friend of mine still have that our drones just fly across the planet to try and help the other player.
This renders me with no drones most of the time, which makes me unable to build stuff. Do you know a fix for this?
