### ISSUE TITLE
ILS ArgumentNullException LogisticShipRenderer.Update()

### ISSUE THREAD

**Issue by sp00ktober** [hubastard/nebula#267]
![3](https://user-images.githubusercontent.com/79335616/116763317-b3aa7b80-aa1d-11eb-9d1f-377135a15b96.png)

investigate when and how this can happen.

**Comment by Jon-Myrstad** [comment]
Was fixed in #270 , can't reproduce it anymore.

**Comment by sp00ktober** [comment]
Thought so too, but seems like that dude on discord can still trigger it somehow.

**Comment by PhantomGamers** [comment]
I just wanted to confirm that this still happens with the latest codebase but I don't know what causes it

**Comment by Therzok** [comment]
A null array is passed to Array.Copy. Which means that the ILS is not initialized.

**Comment by sp00ktober** [comment]
The question is how it still can be uninitialized.

**Comment by Therzok** [comment]
Imo, by having a Session instance which requires all managers and the associated data to be initialized the would consolidate all the state initialization to one placeavoiding ahving to look for 'where' and 'why'.

**Comment by sp00ktober** [comment]
Closed as it was not reported again for a long time.
